---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nikita.
--- DateTime: 28.03.2025 14:27
---

local mt = {}
mt.__index = mt

function mt:update(dt)

end

return {
    new = function(player, world)
        return setmetatable({}, mt)
    end
}